In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv("/content/autism.csv")

In [3]:
data

,A1_Score,A2_Score,A3_Score,A4_Score,A5_Score,A6_Score,A7_Score,A8_Score,A9_Score,A10_Score,...,gender,ethnicity,jundice,austim,contry_of_res,used_app_before,result,age_desc,relation,Class
0,1,1,0,0,1,1,0,1,0,0,...,m,Others,no,no,Jordan,no,5,'4-11 years',Parent,NO
1,1,1,0,0,1,1,0,1,0,0,...,m,'Middle Eastern ',no,no,Jordan,no,5,'4-11 years',Parent,NO
2,1,1,0,0,0,1,1,1,0,0,...,m,?,no,no,Jordan,yes,5,'4-11 years',?,NO
3,0,1,0,0,1,1,0,0,0,1,...,f,?,yes,no,Jordan,no,4,'4-11 years',?,NO
4,1,1,1,1,1,1,1,1,1,1,...,m,Others,yes,no,'United States',no,10,'4-11 years',Parent,YES
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
287,1,1,1,1,1,1,1,1,1,1,...,f,White-European,yes,yes,'United Kingdom',no,10,'4-11 years',Parent,YES
288,1,0,0,0,1,0,1,0,0,1,...,f,White-European,yes,yes,Australia,no,4,'4-11 years',Parent,NO
289,1,0,1,1,1,1,1,0,0,1,...,m,Latino,no,no,Brazil,no,7,'4-11 years',Parent,YES
290,1,1,1,0,1,1,1,1,1,1,...,m,'South Asian',no,no,India,no,9,'4-11 years',Parent,YES
291,0,0,1,0,1,0,1,0,0,0,...,f,'South Asian',no,no,India,no,3,'4-11 years',Parent,NO

In [4]:
data = data.replace('?', -1)

In [5]:
data

,A1_Score,A2_Score,A3_Score,A4_Score,A5_Score,A6_Score,A7_Score,A8_Score,A9_Score,A10_Score,...,gender,ethnicity,jundice,austim,contry_of_res,used_app_before,result,age_desc,relation,Class
0,1,1,0,0,1,1,0,1,0,0,...,m,Others,no,no,Jordan,no,5,'4-11 years',Parent,NO
1,1,1,0,0,1,1,0,1,0,0,...,m,'Middle Eastern ',no,no,Jordan,no,5,'4-11 years',Parent,NO
2,1,1,0,0,0,1,1,1,0,0,...,m,-1,no,no,Jordan,yes,5,'4-11 years',-1,NO
3,0,1,0,0,1,1,0,0,0,1,...,f,-1,yes,no,Jordan,no,4,'4-11 years',-1,NO
4,1,1,1,1,1,1,1,1,1,1,...,m,Others,yes,no,'United States',no,10,'4-11 years',Parent,YES
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
287,1,1,1,1,1,1,1,1,1,1,...,f,White-European,yes,yes,'United Kingdom',no,10,'4-11 years',Parent,YES
288,1,0,0,0,1,0,1,0,0,1,...,f,White-European,yes,yes,Australia,no,4,'4-11 years',Parent,NO
289,1,0,1,1,1,1,1,0,0,1,...,m,Latino,no,no,Brazil,no,7,'4-11 years',Parent,YES
290,1,1,1,0,1,1,1,1,1,1,...,m,'South Asian',no,no,India,no,9,'4-11 years',Parent,YES
291,0,0,1,0,1,0,1,0,0,0,...,f,'South Asian',no,no,India,no,3,'4-11 years',Parent,NO

In [6]:
data=pd.get_dummies(data)

In [7]:
data

,A1_Score,A2_Score,A3_Score,A4_Score,A5_Score,A6_Score,A7_Score,A8_Score,A9_Score,A10_Score,...,used_app_before_yes,age_desc_'4-11 years',relation_-1,relation_'Health care professional',relation_Parent,relation_Relative,relation_Self,relation_self,Class_NO,Class_YES
0,1,1,0,0,1,1,0,1,0,0,...,0,1,0,0,1,0,0,0,1,0
1,1,1,0,0,1,1,0,1,0,0,...,0,1,0,0,1,0,0,0,1,0
2,1,1,0,0,0,1,1,1,0,0,...,1,1,1,0,0,0,0,0,1,0
3,0,1,0,0,1,1,0,0,0,1,...,0,1,1,0,0,0,0,0,1,0
4,1,1,1,1,1,1,1,1,1,1,...,0,1,0,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
287,1,1,1,1,1,1,1,1,1,1,...,0,1,0,0,1,0,0,0,0,1
288,1,0,0,0,1,0,1,0,0,1,...,0,1,0,0,1,0,0,0,1,0
289,1,0,1,1,1,1,1,0,0,1,...,0,1,0,0,1,0,0,0,0,1
290,1,1,1,0,1,1,1,1,1,1,...,0,1,0,0,1,0,0,0,0,1
291,0,0,1,0,1,0,1,0,0,0,...,0,1,0,0,1,0,0,0,1,0

In [16]:
inputs=data.drop("Class_NO",axis=1)
outputs=data['Class_NO']

In [17]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(inputs,outputs,test_size=0.25,random_state=0)
print("x_train\n",x_train)
print("x_test\n",x_test)
print("y_train\n",y_train)
print("y_test\n",y_test)

x_train
      A1_Score  A2_Score  A3_Score  A4_Score  A5_Score  A6_Score  A7_Score  \
153         1         1         1         1         1         1         1
278         1         0         0         0         1         0         0
101         1         1         1         1         0         1         1
228         1         0         0         0         1         0         1
76          1         1         1         1         0         1         1
..        ...       ...       ...       ...       ...       ...       ...
251         0         1         1         1         1         1         1
192         1         1         1         0         1         1         0
117         1         1         0         1         0         1         0
47          1         1         1         0         1         0         1
172         1         1         1         1         1         1         1

     A8_Score  A9_Score  A10_Score  ...  used_app_before_no  \
153         0         1          1  ...                   1
278         1         0          1  ...                   1
101         0         0          1  ...                   1
228         1         0          0  ...                   1
76          1         1          1  ...                   1
..        ...       ...        ...  ...                 ...
251         1         0          1  ...                   1
192         0         1          1  ...                   1
117         0         1          1  ...                   1
47          1         0          1  ...                   1
172         1         1          1  ...                   1

     used_app_before_yes  age_desc_'4-11 years'  relation_-1  \
153                    0                      1            0
278                    0                      1            0
101                    0                      1            0
228                    0                      1            0
76                     0                      1            0
..                   ...                    ...          ...
251                    0                      1            1
192                    0                      1            0
117                    0                      1            0
47                     0                      1            1
172                    0                      1            0

     relation_'Health care professional'  relation_Parent  relation_Relative  \
153                                    0                1                  0
278                                    0                1                  0
101                                    0                1                  0
228                                    1                0                  0
76                                     0                1                  0
..                                   ...              ...                ...
251                                    0                0                  0
192                                    0                0                  1
117                                    0                1                  0
47                                     0                0                  0
172                                    0                1                  0

     relation_Self  relation_self  Class_YES
153              0              0          1
278              0              0          0
101              0              0          1
228              0              0          0
76               0              0          1
..             ...            ...        ...
251              0              0          1
192              0              0          1
117              0              0          0
47               0              0          1
172              0              0          1

[219 rows x 99 columns]
x_test
      A1_Score  A2_Score  A3_Score  A4_Score  A5_Score  A6_Score  A7_Score  \
226         0         0         0         0         1         1         0
284         1         0         1         0         1         1         1
209         1         0         1         1         1         1         0
171         0         0         1         0         1         0         1
118         0         0         0         1         1         1         1
..        ...       ...       ...       ...       ...       ...       ...
37          1         1         0         0         0         0         0
187         1         1         1         1         1         1         1
160         1         0         1         1         1         1         0
214         1         0         1         1         0         1         0
167         1         0         1         1         1         1         1

     A8_Score  A9_Score  A10_Score  ...  used_app_before_no  \
226         1         0          1  ...                   1
284         0         0          1  ...                   1
209         1         0          0  ...                   1
171         0         0          1  ...                   1
118         1         1          0  ...                   1
..        ...       ...        ...  ...                 ...
37          0         0          0  ...                   1
187         1         1          1  ...                   1
160         1         0          1  ...                   1
214         1         1          0  ...                   1
167         1         0          1  ...                   1

     used_app_before_yes  age_desc_'4-11 years'  relation_-1  \
226                    0                      1            0
284                    0                      1            0
209                    0                      1            0
171                    0                      1            0
118                    0                      1            0
..                   ...                    ...          ...
37                     0                      1            0
187                    0                      1            0
160                    0                      1            1
214                    0                      1            0
167                    0                      1            0

     relation_'Health care professional'  relation_Parent  relation_Relative  \
226                                    0                1                  0
284                                    1                0                  0
209                                    0                1                  0
171                                    0                0                  1
118                                    0                0                  1
..                                   ...              ...                ...
37                                     0                1                  0
187                                    0                1                  0
160                                    0                0                  0
214                                    0                1                  0
167                                    0                1                  0

     relation_Self  relation_self  Class_YES
226              0              0          0
284              0              0          0
209              0              0          0
171              0              0          0
118              0              0          0
..             ...            ...        ...
37               0              0          0
187              0              0          1
160              0              0          1
214              0              0          0
167              0              0          1

[73 rows x 99 columns]
y_train
 153    0
278    1
101    0
228    1
76     0
      ..
251    0
192    0
117    1
47     0
172    0
Name: Class_NO, Length: 219, dtype: uint8
y_test
 226    1
284    1
209    1
171    1
118    1
      ..
37     1
187    0
160    0
214    1
167    0
Name: Class_NO, Length: 73, dtype: uint8

In [18]:
from sklearn.preprocessing import StandardScaler
st_x=StandardScaler()
x_train=st_x.fit_transform(x_train)
x_test=st_x.fit_transform(x_test)
print("x_train\n",x_train)
print("x_test\n",x_test)

x_train
 [[ 0.72168784  0.94230093  0.58613845 ... -0.13639887  0.
   1.05155562]
 [ 0.72168784 -1.06123211 -1.70608156 ... -0.13639887  0.
  -0.95097204]
 [ 0.72168784  0.94230093  0.58613845 ... -0.13639887  0.
   1.05155562]
 ...
 [ 0.72168784  0.94230093 -1.70608156 ... -0.13639887  0.
  -0.95097204]
 [ 0.72168784  0.94230093  0.58613845 ... -0.13639887  0.
   1.05155562]
 [ 0.72168784  0.94230093  0.58613845 ... -0.13639887  0.
   1.05155562]]
x_test
 [[-1.13192314 -1.10096377 -1.68585446 ...  0.         -0.11785113
  -1.01379376]
 [ 0.88345221 -1.10096377  0.59317101 ...  0.         -0.11785113
  -1.01379376]
 [ 0.88345221 -1.10096377  0.59317101 ...  0.         -0.11785113
  -1.01379376]
 ...
 [ 0.88345221 -1.10096377  0.59317101 ...  0.         -0.11785113
   0.98639392]
 [ 0.88345221 -1.10096377  0.59317101 ...  0.         -0.11785113
  -1.01379376]
 [ 0.88345221 -1.10096377  0.59317101 ...  0.         -0.11785113
   0.98639392]]

In [19]:
from sklearn.svm import SVC
classifier=SVC(kernel='linear',random_state=0)
classifier.fit(x_train,y_train)

SVC(kernel='linear', random_state=0)

In [20]:
y_pred=classifier.predict(x_test)
y_pred

array([1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 0], dtype=uint8)

In [21]:
from sklearn.metrics import accuracy_score
d=accuracy_score(y_test,y_pred)
print(d*100)

100.0